# 项目标识
sonar.projectKey=com.example
sonar.projectName=user-api-demo
sonar.projectVersion=1.0

# 源码路径
sonar.sources=src/main/java

# 目标编译文件路径（告诉 SonarScanner 去找编译后的class文件，方便代码分析）
sonar.java.binaries=target/classes

# 测试代码路径（如果需要）
# sonar.tests=src/test/java

# SonarQube服务器地址
sonar.host.url=http://localhost:9000

# SonarQube访问Token
sonar.login=sqa_9e2e5c9a3609ab730cc74bfb697ba0743a816493

# 代码覆盖率报告路径（如果用 JaCoCo 生成了覆盖率报告）
# sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

git remote set-url origin git@gitlab.com:com.example3850027/user-api-demo.git

